# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  pre = "briefcase"
  name = "Portfolio"
  weight = 10
  url = "/portfolio"

[[main]]
  pre = "user-account"
  name = "About"
  weight = 20
  url = "/about"

[[main]]
  pre = "newspaper-clipping"
  name = "Artikel"
  weight = 20
  url = "/artikel"

# =====================Belajar======================

[[main]]
  pre = "graduation-cap"
  name = "Belajar"
  weight = 20
  url = "/belajar"

[[main]]
  pre = "source-code"
  name = "Computer Programming"
  parent = "Belajar"
  weight = 20
  url = "/belajar/programming"

[[main]]
  pre = "erp"
  name = "Enterprise Resource Planning"
  parent = "Belajar"
  weight = 20
  url = "/belajar/erp"

# =====================Lainnya======================

[[main]]
  pre = "option"
  name = "Lainnya"
  weight = 20
  url = "/lainnya"

[[main]]
  pre = "notebook"
  name = "Pengalaman"
  parent = "Lainnya"
  weight = 20
  url = "/lainnya/Pengalaman"

[[main]]
  pre = "award"
  name = "Sertifikat"
  parent = "Lainnya"
  weight = 20
  url = "/lainnya/sertifikat"

# =====================Penutup======================

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/King-Ulee"
  weight = 25

[[main]]
  identifier = "twitter"
  pre = "twitter"
  url = "https://twitter.com/king_ulee"
  weight = 30

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20